### ISSUE TITLE
AccessToken is empty if we use Newtonsoft.Json 9.0 version

### ISSUE THREAD

**Issue by sdonepudi** [Axosoft/AxosoftAPI.NET#10]
Hi,

axosoftClient.ObtainAccessTokenFromUsernamePassword method is failing if we use latest Newtonsoft.Json version 9.0.1

The API perfectly works for Newtonsoft.Json version 6.00

**Comment by BrettGAxosoft** [comment]
I was unable to reproduce any issues using Newtonsoft.JSON 9.0.1.  If you continue to experience issues, you can view the example code in our API examples here: http://developer.axosoft.com/docs/AxosoftAPIWebinarExample.zip
